server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./h2/testdb
    #    url: jdbc:h2:file:./h2/integrationtestdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    hibernate:
      ddl-auto: none
    show-sql: true
    console:
      enabled: true
  flayway:
    locations:classpath:db/migration